serial:
  devices:
    - /tmp/tty_gateway
  baud_rate: 115200
  reconnect_interval_seconds: 2

mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: sensor
  cache_retry_interval_seconds: 2
  username: ""
  password: ""
  tls:
    enabled: false
    ca_file: ""
    certificate_file: ""
    private_key_file: ""
    insecure: false

tcp:
  enabled: true
  host: tcp-server
  port: 9000

http:
  enabled: true
  host: 0.0.0.0
  port: 8080

cache:
  type: sqlite
  path: /app/artifacts/docker/pending_messages.db

log:
  path: /app/artifacts/docker/gateway.log
  level: INFO
